local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.config/nvim/plugged")

Plug("nvim-lua/plenary.nvim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("RRethy/nvim-treesitter-endwise")
Plug("nvim-telescope/telescope.nvim")
Plug("kana/vim-textobj-user")
Plug("nelstrom/vim-textobj-rubyblock")
Plug("gcmt/wildfire.vim")
Plug("RRethy/vim-illuminate")
Plug("kyazdani42/nvim-web-devicons")
Plug("kyazdani42/nvim-tree.lua")
Plug("mg979/vim-visual-multi")
Plug("phaazon/hop.nvim")
Plug("ethanholz/nvim-lastplace")
Plug("tpope/vim-surround")
Plug("tpope/vim-repeat")
Plug("arthurxavierx/vim-caser")
Plug("akinsho/bufferline.nvim", { ["tag"] = "v3.*" })
Plug("godlygeek/tabular")
Plug("LunarWatcher/auto-pairs")
Plug("christoomey/vim-tmux-runner")
Plug("christoomey/vim-tmux-navigator")
Plug("MattesGroeger/vim-bookmarks")
Plug("AndrewRadev/splitjoin.vim")
Plug("nvim-lualine/lualine.nvim")
Plug("andymass/vim-matchup")
Plug("folke/which-key.nvim")
Plug("lukas-reineke/indent-blankline.nvim")
-- LSP Support
Plug("neovim/nvim-lspconfig")
Plug("williamboman/mason.nvim")
Plug("williamboman/mason-lspconfig.nvim")
Plug("j-hui/fidget.nvim")
Plug("jose-elias-alvarez/null-ls.nvim")
Plug("lukas-reineke/lsp-format.nvim")
-- Autocompletion
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/cmp-buffer")
Plug("hrsh7th/cmp-path")
Plug("saadparwaiz1/cmp_luasnip")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("hrsh7th/cmp-nvim-lua")
-- Snippets
Plug("L3MON4D3/LuaSnip")
Plug("rafamadriz/friendly-snippets")
-- Auto LSP Configuration
Plug("VonHeikemen/lsp-zero.nvim")
-- Commenting
Plug("numToStr/Comment.nvim")
Plug("JoosepAlviste/nvim-ts-context-commentstring")
-- Git
Plug("tanvirtin/vgit.nvim")
Plug("tpope/vim-fugitive")
Plug("ruifm/gitlinker.nvim")
Plug("rhysd/conflict-marker.vim")
-- HTML
Plug("windwp/nvim-ts-autotag")
Plug("Shougo/context_filetype.vim")
-- Ruby
Plug("tpope/vim-rails")
Plug("vim-test/vim-test")
-- Misc
Plug("editorconfig/editorconfig-vim")
Plug("moll/vim-bbye")
Plug("petertriho/nvim-scrollbar")
Plug("kevinhwang91/nvim-hlslens")
-- Theme
Plug("EdenEast/nightfox.nvim")
Plug("folke/tokyonight.nvim", { ["branch"] = "main" })
Plug("rcarriga/nvim-notify")
Plug("eandrju/cellular-automaton.nvim")
vim.call("plug#end")

require("plugins.theme")
require("plugins.treesitter")
require("plugins.lsp-zero")
require("plugins.illuminate")
require("plugins.nvim-tree")
require("plugins.tabularize")
require("plugins.wildfire")
require("plugins.editor_config")
require("plugins.vtr")
require("plugins.conflict_marker")
require("plugins.auto-pairs")
require("plugins.vim_test")
require("plugins.splitjoin")
require("plugins.hop")
require("plugins.vgit")
require("plugins.gitlinker")
require("plugins.matchup")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.floaterm")
require("plugins.which-key")
require("plugins.indent_blankline")
require("plugins.nvim-notify")
require("plugins.bufferline")
require("plugins.fugitive")
require("plugins.nvim-scrollbar")
require("plugins.nvim-hlslens")
require("plugins.comment-nvim")

require("nvim-lastplace").setup({})
