local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.config/nvim/plugged")

Plug("nvim-lua/plenary.nvim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("RRethy/nvim-treesitter-endwise")
Plug("nvim-telescope/telescope.nvim")
Plug("kana/vim-textobj-user")
Plug("nelstrom/vim-textobj-rubyblock")
Plug("RRethy/vim-illuminate")
Plug("kyazdani42/nvim-web-devicons")
Plug("kyazdani42/nvim-tree.lua")
Plug("honza/vim-snippets")
Plug("mg979/vim-visual-multi")
Plug("phaazon/hop.nvim")
Plug("farmergreg/vim-lastplace")
Plug("tanvirtin/vgit.nvim")
Plug("tpope/vim-fugitive")
Plug("ruifm/gitlinker.nvim")
Plug("tpope/vim-surround")
Plug("tpope/vim-repeat")
Plug("arthurxavierx/vim-caser")
Plug("akinsho/bufferline.nvim", { ["tag"] = "v3.*" })
Plug("godlygeek/tabular")
Plug("tyru/caw.vim")
Plug("rhysd/conflict-marker.vim")
Plug("LunarWatcher/auto-pairs")
Plug("sheerun/vim-polyglot")
Plug("christoomey/vim-tmux-runner")
Plug("christoomey/vim-tmux-navigator")
Plug("MattesGroeger/vim-bookmarks")
Plug("AndrewRadev/splitjoin.vim")
Plug("nvim-lualine/lualine.nvim")
Plug("w0rp/ale")
Plug("neoclide/coc.nvim", { ["branch"] = "release" })
Plug("fannheyward/telescope-coc.nvim")
Plug("gcmt/wildfire.vim")
Plug("andymass/vim-matchup")
Plug("voldikss/vim-floaterm")
Plug("folke/which-key.nvim")
Plug("lukas-reineke/indent-blankline.nvim")
Plug("rcarriga/nvim-notify")
-- HTML
Plug("windwp/nvim-ts-autotag")
Plug("Shougo/context_filetype.vim")
-- Ruby
Plug("tpope/vim-rails")
Plug("vim-test/vim-test")
-- Misc
Plug("editorconfig/editorconfig-vim")
Plug("moll/vim-bbye")
-- Theme
Plug("EdenEast/nightfox.nvim")
vim.call("plug#end")

require("plugins.theme")
require("plugins.treesitter")
require("plugins.illuminate")
require("plugins.nvim-tree")
require("plugins.tabularize")
require("plugins.wildfire")
require("plugins.editor_config")
require("plugins.coc")
require("plugins.ale")
require("plugins.vtr")
require("plugins.conflict_marker")
require("plugins.auto-pairs")
require("plugins.vim_test")
require("plugins.splitjoin")
require("plugins.hop")
require("plugins.vgit")
require("plugins.gitlinker")
require("plugins.matchup")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.floaterm")
require("plugins.which-key")
require("plugins.indent_blankline")
require("plugins.nvim-notify")
require("plugins.bufferline")
require("plugins.fugitive")
